# Generated by Django 5.0.2 on 2025-04-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='Participants',
            field=models.ManyToManyField(blank=True, to='meetups.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
