# Generated by Django 5.0.2 on 2025-04-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_alter_meetup_participants_alter_participant_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='Participants',
            new_name='participants',
        ),
    ]
